server:
  port: 8899
  context-path: /wxeat
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://47.98.180.12:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#logging:
 # pattern:
 #   console: "%d - %msg%n"
#  path: C:\Users\Administrator\Desktop\idea
#  file: C:\Users\Administrator\Desktop\idea\sell.log
#  level: debug
